using System.Globalization;
using BudgetGuard.Domain.Detection.Explanations;

namespace BudgetGuard.Domain.Detection.Benford;

/// <summary>Tests a population of monetary amounts for first-digit conformity to Benford's Law.</summary>
public interface IBenfordAnalyzer
{
    /// <summary>Runs the conformity test over <paramref name="amounts"/>.</summary>
    BenfordResult Analyze(IEnumerable<decimal> amounts, string populationLabel);
}

/// <summary>
/// First-digit distribution analysis (Benford's Law).
/// <para>
/// <b>Why this works.</b> In data that spans several orders of magnitude and
/// arises from multiplicative processes — which procurement spending does — the
/// leading digit is not uniformly distributed. The probability that a value
/// begins with digit <i>d</i> is log10(1 + 1/d): about 30.1% of natural amounts
/// start with 1, and only 4.6% start with 9. The reason is scale invariance. If
/// a quantity is equally likely to be measured in any unit, its logarithm is
/// roughly uniform, and a uniform mantissa produces exactly this digit law.
/// </para>
/// <para>
/// <b>Why it catches fraud.</b> People inventing numbers do not reproduce that
/// curve. Fabricated invoices cluster on round figures and on digits just under
/// approval limits — a 5,000,000 sign-off ceiling produces a glut of amounts
/// starting with 4. Benford does not identify a guilty transaction; it says
/// "this population was not generated by the process that generates honest
/// spending", which is precisely the cue to pull the ledger.
/// </para>
/// <para>
/// <b>Verdict method.</b> Mean Absolute Deviation is the primary test, using
/// Nigrini's published conformity bands. Chi-square is computed and reported,
/// but deliberately not used as the verdict: it scales with sample size, so on
/// tens of thousands of rows it rejects conformity for deviations far too small
/// to mean anything. See docs/DETECTION_METHODOLOGY.md.
/// </para>
/// </summary>
public sealed class BenfordAnalyzer : IBenfordAnalyzer
{
    private readonly BenfordSettings _settings;

    /// <summary>Benford expected proportions for digits 1-9, index 0 = digit 1.</summary>
    private static readonly double[] ExpectedProportions =
        Enumerable.Range(1, 9).Select(d => Math.Log10(1d + 1d / d)).ToArray();

    /// <summary>
    /// Coefficient in the expected-MAD-under-the-null formula, 0.7979 x mean of
    /// sqrt(p(1-p)) across the nine Benford proportions.
    /// <para>
    /// If a sample of size n genuinely follows Benford's Law, each observed
    /// proportion still wobbles around its expectation with standard error
    /// sqrt(p(1-p)/n), and the mean absolute value of a zero-centred normal is
    /// 0.7979 of its standard deviation. Averaging across the nine digits gives
    /// an expected MAD of roughly 0.2348/sqrt(n) from chance alone.
    /// </para>
    /// </summary>
    private const double NullMadCoefficient = 0.2348;

    private readonly IExplanationWriter _writer;

    /// <param name="settings">Thresholds. See <see cref="BenfordSettings"/>.</param>
    /// <param name="writer">
    /// Language the verdict sentence is written in. Defaults to English, which
    /// is the reference rendering the API serves and the test suite asserts on.
    /// </param>
    public BenfordAnalyzer(BenfordSettings settings, IExplanationWriter? writer = null)
    {
        _settings = settings ?? throw new ArgumentNullException(nameof(settings));
        _writer = writer ?? new EnglishExplanationWriter();
    }

    /// <summary>
    /// The Mean Absolute Deviation expected purely from sampling noise for a
    /// perfectly Benford-conforming sample of <paramref name="sampleSize"/>
    /// records. Any verdict must clear this before it means anything.
    /// </summary>
    /// <param name="sampleSize">Number of usable amounts.</param>
    public static double ExpectedMadFromSamplingNoise(int sampleSize) =>
        sampleSize <= 0 ? double.PositiveInfinity : NullMadCoefficient / Math.Sqrt(sampleSize);

    /// <summary>Expected Benford proportion for a leading digit, log10(1 + 1/d).</summary>
    /// <param name="digit">Leading digit, 1-9.</param>
    public static double ExpectedProportion(int digit)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(digit, 1);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(digit, 9);
        return ExpectedProportions[digit - 1];
    }

    /// <summary>
    /// Extracts the first significant (non-zero) digit of a monetary amount.
    /// <para>
    /// Works on the decimal's own digit string rather than by repeated
    /// multiplication or division. Money is stored as <see cref="decimal"/>
    /// precisely so its digits are exact; normalising through binary floating
    /// point could turn 0.3 into 0.2999... and silently change the leading
    /// digit of the very value under test.
    /// </para>
    /// </summary>
    /// <param name="amount">Amount to inspect. Must be positive to yield a digit.</param>
    /// <returns>The leading digit 1-9, or null when the amount is zero or negative.</returns>
    public static int? LeadingDigit(decimal amount)
    {
        if (amount <= 0m)
        {
            return null;
        }

        foreach (var c in amount.ToString(CultureInfo.InvariantCulture))
        {
            if (c is >= '1' and <= '9')
            {
                return c - '0';
            }
        }

        return null;
    }

    /// <inheritdoc />
    public BenfordResult Analyze(IEnumerable<decimal> amounts, string populationLabel)
    {
        ArgumentNullException.ThrowIfNull(amounts);

        var counts = new int[9];
        var sampleSize = 0;
        var excluded = 0;

        foreach (var amount in amounts)
        {
            var digit = LeadingDigit(amount);
            if (digit is null)
            {
                // Zero, negative and credit-note rows carry no first-digit
                // information. Counted and reported, never silently dropped.
                excluded++;
                continue;
            }

            counts[digit.Value - 1]++;
            sampleSize++;
        }

        if (sampleSize < _settings.MinimumSampleSize)
        {
            return new BenfordResult(
                sampleSize,
                excluded,
                BuildBuckets(counts, sampleSize),
                MeanAbsoluteDeviation: 0d,
                ChiSquare: 0d,
                _settings.ChiSquareCriticalValue,
                BenfordConformity.InsufficientData,
                _writer.BenfordInsufficientData(populationLabel, sampleSize, _settings.MinimumSampleSize),
                populationLabel,
                EffectiveThreshold(sampleSize));
        }

        var buckets = BuildBuckets(counts, sampleSize);

        var mad = buckets.Average(b => Math.Abs(b.ObservedProportion - b.ExpectedProportion));
        var chiSquare = buckets.Sum(b =>
            Math.Pow(b.ObservedCount - b.ExpectedCount, 2) / b.ExpectedCount);

        var conformity = ClassifyConformity(mad, sampleSize);
        var effectiveThreshold = EffectiveThreshold(sampleSize);

        return new BenfordResult(
            sampleSize,
            excluded,
            buckets,
            mad,
            chiSquare,
            _settings.ChiSquareCriticalValue,
            conformity,
            _writer.Benford(new BenfordExplanationContext(
                populationLabel,
                sampleSize,
                mad,
                effectiveThreshold,
                _settings.MadNonConformityThreshold,
                ExpectedMadFromSamplingNoise(sampleSize),
                chiSquare,
                _settings.ChiSquareCriticalValue,
                conformity,
                buckets.MaxBy(b => b.DeviationPercentagePoints)!)),
            populationLabel,
            effectiveThreshold);
    }

    /// <summary>
    /// The MAD a deviation must exceed to be called non-conformant at this
    /// sample size: the larger of Nigrini's fixed band and the sampling-noise
    /// floor. On large populations the fixed band governs; on a small vendor's
    /// invoice set the noise floor governs, which is what stops the analyser
    /// from flagging every supplier that happens to have few invoices.
    /// </summary>
    private double EffectiveThreshold(int sampleSize) =>
        Math.Max(
            _settings.MadNonConformityThreshold,
            _settings.NoiseFloorMultiple * ExpectedMadFromSamplingNoise(sampleSize));

    /// <summary>Maps a MAD value onto Nigrini's conformity bands, scaled for sample size.</summary>
    private BenfordConformity ClassifyConformity(double mad, int sampleSize)
    {
        if (mad >= EffectiveThreshold(sampleSize))
        {
            return BenfordConformity.NonConformant;
        }

        if (mad < _settings.MadCloseConformityThreshold)
        {
            return BenfordConformity.Close;
        }

        return mad < _settings.MadAcceptableConformityThreshold
            ? BenfordConformity.Acceptable
            : BenfordConformity.MarginallyAcceptable;
    }

    private static List<BenfordDigitBucket> BuildBuckets(int[] counts, int sampleSize)
    {
        var buckets = new List<BenfordDigitBucket>(9);

        for (var i = 0; i < 9; i++)
        {
            var expectedProportion = ExpectedProportions[i];
            buckets.Add(new BenfordDigitBucket(
                Digit: i + 1,
                ObservedCount: counts[i],
                ObservedProportion: sampleSize == 0 ? 0d : (double)counts[i] / sampleSize,
                ExpectedCount: expectedProportion * sampleSize,
                ExpectedProportion: expectedProportion));
        }

        return buckets;
    }

}
